name: Issue submitted

on:
  issues:
    types: [opened, edited, milestoned]

jobs:
  create-pr:
    name: Create new PR
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
